# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20160812_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='activation_key',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='myuser',
            name='key_expiration',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
